PY = python3
EXT=-r local
File1 = "small.txt"
File2 = "large.txt"
File3 = "very_large.txt"

#Part 1
part1_s:
	${PY} lab3-part1.py ${File1} ${EXT}

part1_l:
	${PY} lab3-part1.py ${File2} ${EXT}

part1_vl:
	${PY} lab3-part1.py ${File3} ${EXT}

#Part 2
part2_k10_s:
	${PY} lab3-part2-k10.py ${File1} ${EXT}

part2_k10_l:
	${PY} lab3-part2-k10.py ${File2} ${EXT}

part2_k10_vl:
	${PY} lab3-part2-k10.py ${File3} ${EXT}

part2_k20_s:
	${PY} lab3-part2-k20.py ${File1} ${EXT}

part2_k20_l:
	${PY} lab3-part2-k20.py ${File2} ${EXT}

part2_k20_vl:
	${PY} lab3-part2-k20.py ${File3} ${EXT}

#Part 3
part3_s:
	${PY} lab3-part3.py ${File1} ${EXT}

part3_l:
	${PY} lab3-part3.py ${File2} ${EXT}

part3_vl:
	${PY} lab3-part3.py ${File3} ${EXT}